### ISSUE TITLE
Regression to task.children in 1.28

### ISSUE THREAD

**Issue by paul** [socketry/async#85]
I have an app that I run with falcon, and when I updated to async ~> 1.28, this test started erroring:

```ruby
    Console.logger.debug!
    task = reactor.async do
      resp = app.call(env)
      expect(resp).to eq [204, [], ""]
    end

    task.children.each(&:stop)

    task.wait

    expect(task.status).to eq :complete
```

The error:

```
     Failure/Error: task.children.each(&:stop)

     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./spec/integration_spec.rb:49:in `block (2 levels) in <top (required)>'
```

The app accepts data from an HTTP request, then parses the data and dumps it into different buffer workers. Each buffer has a periodic timer task that occasionally flushes the buffer, and the `#stop` method tells each worker to flush the buffer now instead of waiting for the timer. This works in `1.24` up through `1.27.0`, but now `children` is `nil` in `1.28.1` (`1.28.0` fails with the IO error fixed in .1). 

I tried looking at the diff to see if it was something obvious I could fix myself, but nothing stuck out. https://github.com/socketry/async/compare/v1.27.0...v1.28.1

I actually haven't touched this code in a year (since 1.24), is there a better way to ensure all the subtasks have "cleaned up" within a reactor?

**Comment by ioquatix** [comment]
If `children` is nil, it's the same as `children` being empty.

So, use this: `task.children&.each(&:stop)`.

**Comment by paul** [comment]
Sure, in fact, I changed it to `task.traverse(&:stop)`. However, `children` being nil isn't the problem, its that in 1.27 it had the subtasks in it, but in 1.28 its empty. My test goes on to check the output from flushing the buffers, and in `< 1.28` each subtask receives the `#stop`, so the buffer gets flushed, so the output is present. In `1.28`, children is nil/empty, so the subtasks never receive `#stop`, nothing gets flushed, and the spec failed because there is no output.

**Comment by ioquatix** [comment]
Hmmmm, that's odd. So you are saying there are children tasks but they are not registered with the child? What tasks are you expecting?

**Comment by paul** [comment]
Sorry, I got distracted with other work projects. I've boiled down a simple test case:

```ruby
  fit "simple test case" do
    class MyApp
      def call(_)
        spawn_timer
      end

      def spawn_timer
        Timer.new.call
      end

      class Timer
        def call
          @timer = Async do |task|
            puts "timer started"
            task.sleep 5
            puts "timer finished"
          end
        end

        def stop
          @timer.stop
        end
      end
    end

    task = reactor.async do
      app.call(env)
    end

    task.children.each(&:stop)
    task.wait
  end
```

In < 1.28, `task.children` contained the Timer object(s), and I was able to iterate through them. In `1.28.3`, `children` is empty, and `traverse` does nothing.

Is there a different way to accomplish this? In a test, to ensure all the async tasks that may have been started are given a chance to clean up?

My actual application code is written to buffer data in an array, then periodically flush the buffer to an async http client. I want that flush to be triggered on shutdown. This integration test is for that behavior, and the `task.wait` doesn't trigger that flush, so the next assertion in the test doesn't find any data that got written. The logs for the test also show the client didn't attempt a request.

**Comment by paul** [comment]
Well, I guess that example wouldn't have worked anyways, since `task.childen` would be task object, not my Timer objects. I guess I have to keep track of the timer objects that get created in MyApp? Are there lifecycle hooks for tasks, so I can flush the buffer on `stop` or something similar?

**Comment by ioquatix** [comment]
I will take a look at your example and get back to you.

**Comment by paul** [comment]
I was poking around at my code a bit more by throwing `puts` all over the place, and I think the problem may be that I have to make an AWS DynamoDB request on the first `#call` (and cache the result), using the regular AWS client lib, which isn't async-aware. So in the test, the `task.wait` doesn't "see" that request is happening, thinks the task is done, and shuts everything down. My timer/buffer code never even gets invoked. If I throw a regular `sleep 1` before the `task.wait` in the spec, then I can see some of the tasks in my application code getting started, but its not reliable, and I haven't boiled it down to a simple test case.

**Comment by ioquatix** [comment]
> Well, I guess that example wouldn't have worked anyways, since task.childen would be task object, not my Timer objects. I guess I have to keep track of the timer objects that get created in MyApp? Are there lifecycle hooks for tasks, so I can flush the buffer on stop or something similar?

You just need to use `ensure`, e.g.

```
ensure
  clean_up_timers
```

**Comment by ioquatix** [comment]
```
#!/usr/bin/env ruby

require 'async'

class MyApp
	def call(_)
		spawn_timer
	end

	def spawn_timer
		Timer.new.call
	end

	class Timer
		def call
			@timer = Async do |task|
				puts "timer started"
				task.sleep 5
				puts "timer finished"
			end
		end

		def stop
			@timer.stop
		end
	end
end

app = MyApp.new

Async do |task|
	env = {}
	
	child = Async do
		app.call(env)
	end
	
	child.stop
	child.wait
end
```

Does this do what you want?

**Comment by ioquatix** [comment]
Let me know if you require further assistance.

**Comment by paul** [comment]
@ioquatix Sorry, this project got put on the back burner for a bit. I'll let you know if I run into trouble later. Thanks!
